varlociraptor/varlociraptor

- CHANGELOG.md
- Cargo.toml
- README.md
* updated CHANGELOG (please check for completeness and correctness, @johanneskoester)
* included credits for my own contributions in Cargo.toml and README.md
* updated rust-bio dependency and version number in Cargo.toml
> Prepare v0.4.0

- CHANGELOG.md
- Cargo.toml
- README.md
Sorry, no write access for me on the master branch--so I'll go through this branch and see how far I get.
> New Version

- README.md
Changes discussed a while ago via eMail with @aschoen, @alicemchardy, @johanneskoester. A quick consistency check and a review of the structure would be appreciated.
> update affiliations and attributions in README.md

- CHANGELOG.md
- Cargo.toml
- src/call/pairwise.rs
- src/lib.rs
- src/model/evidence/fragments.rs
- src/model/priors/single_cell_bulk.rs
- src/utils.rs
This closes issue #49, preparing a new release with a ton of changes -- see the CHANGELOG.md for details.
> Prepare v0.7.0

- src/utils.rs
> Removed dbg-macro

- src/estimation/tumor_mutational_burden.rs
- templates/plots/vaf_curve_strat.json
- templates/plots/vaf_hist.json
This PR adds stratified histogram plots for tmb and a new color scheme for vega-lite.
> Tmb plotting

- .cargo/config
- src/utils.rs
This PR adds a config file with linker arguments required for building on macOS.
> Added linker arguments for macOS

- src/calling/variants/calling.rs
- src/calling/variants/mod.rs
- src/calling/variants/preprocessing/mod.rs
- src/cli.rs
- src/variants/evidence/observation.rs
- src/variants/evidence/realignment/edit_distance.rs
- src/variants/evidence/realignment/mod.rs
- src/variants/evidence/realignment/pairhmm.rs
- src/variants/model/bias/divindel_bias.rs
- src/variants/model/bias/mod.rs
- src/variants/model/bias/read_orientation_bias.rs
- src/variants/model/bias/read_position_bias.rs
- src/variants/model/bias/softclip_bias.rs
- src/variants/model/bias/strand_bias.rs
- src/variants/model/likelihood.rs
- src/variants/model/mod.rs
- src/variants/sample.rs
- src/variants/types/breakends.rs
- src/variants/types/deletion.rs
- src/variants/types/insertion.rs
- src/variants/types/mnv.rs
- src/variants/types/mod.rs
- src/variants/types/replacement.rs
- src/variants/types/snv.rs
- tests/common/mod.rs
- tests/lib.rs
- tests/resources/testcases/issue_154/testcase.yaml
- tests/resources/testcases/test34/testcase.yaml
- tests/resources/testcases/test49/testcase.yaml
- tests/resources/testcases/test59/testcase.yaml
> fix: improved divindel bias estimation precision (getting rid of false negatives due to erroneous divindel bias estimates)

- src/calling/variants/preprocessing/mod.rs
- src/cli.rs
- src/variants/types/replacement.rs
- tests/common/version0.rs
> fix: fix out of bounds error when evaluating replacement records

- src/calling/variants/preprocessing/mod.rs
- src/errors.rs
- src/utils/collect_variants.rs
> fix: understandable error message if BCF record contains invalid position

- src/calling/variants/calling.rs
- src/calling/variants/mod.rs
- src/variants/model/likelihood.rs
> feat: output sampled VAF densities (in the AFD format tag)

- src/calling/variants/mod.rs
This PR sorts resulting event probabilities such that they are ordered by descending probability in the final BCF. This allows identifying the event with largest probability easily with a quick glance (with bcftools view).
We could also order by event name instead, such that the info fields are in a consistent (instead of informative) order.
The main point here is that the order is no longer arbitrary.
> fix: sort events by probability for more informative VCF INFO field order

- Cargo.lock
- src/variants/model/mod.rs
Follow-up PR to #263. This PR also updates the Cargo.lock file, so dependencies might have gotten some slight version bumps.
> fix: remove conflicting From<&str> implementation

- src/grammar/formula.rs
> fix: improved display of VAF sets in unnormalized formulas

- Cargo.lock
- Cargo.toml
- src/calling/variants/calling.rs
- src/calling/variants/preprocessing/mod.rs
- tests/resources/testcases/test42/candidates.vcf
> perf: use rust-htslib 0.40.2

- src/grammar/mod.rs
- src/variants/types/insertion.rs
> feat: allow definition of sexes other than female or male

- Cargo.lock
- src/calling/variants/calling.rs
- src/calling/variants/mod.rs
- src/grammar/vaftree.rs
- src/utils/mod.rs
- src/variants/model/mod.rs
- src/variants/model/modes/generic.rs
> fix: constrain MAP estimates of AF to the most probable event

- src/calling/variants/calling.rs
- src/calling/variants/mod.rs
- src/cli.rs
- src/estimation/contamination.rs
- src/grammar/vaftree.rs
- src/testcase/runner/common/mod.rs
- src/testcase/runner/common/version1.rs
- src/testcase/runner/common/version2.rs
- src/variants/evidence/observations/pileup.rs
- src/variants/model/mod.rs
> feat: report number of omitted observations

- src/cli.rs
- src/estimation/contamination.rs
- templates/plots/contamination_estimation.json
> fix: improved plotting for contamination estimation

- src/calling/variants/mod.rs
- src/calling/variants/preprocessing/mod.rs
- src/cli.rs
- src/testcase/runner/common/mod.rs
- src/variants/model/mod.rs
> fix: improved debug and observation output

- src/errors.rs
- src/filtration/fdr.rs
- src/utils/mod.rs
> feat: in FDR control, skip events that do not occur in the BCF header. Error if no event matches, warn otherwise.

- src/estimation/mutational_burden.rs
> feat: warn on missing ANN records in mutational burden estimation

- src/grammar/formula.pest
- src/grammar/formula.rs
- src/grammar/vaftree.rs
- src/variants/model/modes/generic.rs
> feat: implement "true" formula terminal

- environment.yml
> chore: add test environment

- src/variants/evidence/realignment/edit_distance.rs
- src/variants/evidence/realignment/mod.rs
- src/variants/evidence/realignment/pairhmm.rs
- src/variants/types/breakends.rs
- src/variants/types/deletion.rs
- src/variants/types/insertion.rs
- src/variants/types/mnv.rs
- src/variants/types/replacement.rs
- src/variants/types/snv.rs
> fix: out of bounds error in estimation of third allele probability

- src/utils/mod.rs
This PR makes  #414 actually usable by making the mod public as well.
> refactor: Make collect variant mod public

- src/grammar/vaftree.rs
- src/utils/collect_variants.rs
- src/utils/mod.rs
- src/variants/model/bias/mod.rs
- src/variants/model/mod.rs
Another addition to the last PR making all types and enums of the mod public.
> refactor: Make remaining parts of variant module public

- src/variants/evidence/observations/read_observation.rs
- src/variants/model/bias/alt_locus_bias.rs
- src/variants/sample.rs
> fix: fix bug during calculation of read position bias

- src/calling/variants/mod.rs
- src/utils/collect_variants.rs
- src/variants/model/bias/mod.rs
- src/variants/model/bias/read_position_bias.rs
- tests/resources/testcases/test20/testcase.yaml
- tests/resources/testcases/test70/testcase.yaml
- tests/resources/testcases/test_cmp/testcase.yaml
- tests/resources/testcases/test_l2fc/testcase.yaml
> fix: improved specificity of read position bias model by estimating the rate of the predominant read position from the ref supporting observations

- Cargo.toml
- src/utils/homopolymers.rs
This PR updates the `bio` dependency.
> chore: Update bio dependency

- Cargo.lock
> build: Update Cargo.lock file
