varlociraptor/varlociraptor

Cargo.toml, src/call/pairwise.rs, src/estimation/fdr.rs, src/model/likelihood.rs, src/model/mod.rs, src/model/priors/flat.rs, src/model/priors/single_cell_bulk.rs, src/model/priors/tumor_normal.rs, src/model/sample.rs
For indels, we now sample reads that overlap the start or end of the variant by a configurable maximum. This ensures that alt and ref reads are sampled without bias.
Otherwise, the bias is as follows. If the overlap is too large, an alt read is (a) softclipped but with reduced MAPQ, (b) hardclipped such that the alt sequence is lost, (c) not mapped at all. All three cases are unfair compared to the ref reads and lead to biased allele frequency estimates.
=> Constrained sampling of read overlaps

src/estimation/fdr/bh.rs, src/estimation/fdr/ev.rs, src/utils.rs, tests/lib.rs, tests/resources/test_collect_prob_dist/min.calls.vcf
Changes `collect_prob_dist()` signature to take sets of `Event`s as input and adds tests for the function, based on variants and a header stolen from the `tests/resources/test_fdr_ev_1/calls.matched.bcf`.
The branch still doesn't pass on Travis, so I'm now trying via the pull request.
@johanneskoester Please do double check the changes I made, especially if the assumptions in the tests make sense (e.g. that the highest / only prob in the returned vectors is always in the last position of the returned vector).
=> FDR for vectors of `Event`s / sets of `Event`s

src/utils.rs
Trying to filter the BCF file based on compound false discovery rate (FDR) thresholds for `Event` sets that were generated by the `control-fdr` subcommand of prosolo, I realised that `bcftools` cannot easily filter on (useful) combinations of multiple PHRED scores. So I implemented this functionality as the backend of an `apply-fdr` subcommand for prosolo.
In the midterm, it might be useful to generate a separate CLI tool only for controlling the false discovery rate, because this should be agnostic of the libprosic CLI tool used for generating the `Event` probabilities. I created issue #16 to track this idea.
Also, could we make this a release 0.5.1, as it effectively closes a gap in the FDR functionality from version 0.5.0? Or would semantic versioning rather require a release 0.6.0?
=> add utils.rs function to filter by FDR thresholds

Cargo.toml, src/call/pairwise.rs, src/estimation/effective_mutation_rate.rs, src/estimation/fdr/bh.rs, src/estimation/fdr/ev.rs, src/estimation/fdr/mod.rs, src/lib.rs, src/model/mod.rs, src/model/sample.rs
This mirrors an update in `rust-bio 0.15` compared to `rust-bio 0.14` (I will need this update and actually an update to the next future release of `rust-bio` to enable the new `cap_numerical_overshoot()` function for `LogProb`s from `rust-bio` here in `libprosic`).
@johanneskoester:
While this branch compiles properly, 4 tests fail with a FloatParsingError on field 8 of the first record in the observation csv files example[2347].obs.txt in the new csv function `deserialize()` (<https://docs.rs/csv/1.0.0-beta.5/csv/struct.Reader.html#method.deserialize>).
Any ideas what might have changed in comparison to the `decode()` function in csv 0.15.0 (<https://docs.rs/csv/0.15.0/csv/struct.Reader.html#method.decode>)? It sounds like something to do with the `collect()` into the `Observation` …
=> move from rustc-serialize dep to csv 1.0.0-beta.5

src/utils.rs, tests/resources/test_tags_prob_sum/overshoot.vcf
* use numerically more stable `ln_sum_exp()` on vector with collection of Event probs
**Please don't merge, until the following is addressed:**
A second goal (further commits needed!) is to resolve numerical issues in summing up `Event` probabilities. @johanneskoester, would you have some recommendations regarding the following issue and my idea to resolve it?
I have now factored out the summing up of `Event`probabilities into a separate function that also is used in control-fdr and that first collects the probabilities at a site into a vector and the runs `ln_sum_exp()` on it. Nevertheless, control-fdr chokes on some sites, where the sum of the probabilities is slightly above of certain `Event`s is above one, e.g. the following line:
```
chr1	62976472	rs1168043	T	G	5682.93	PASS …
```
=> abstract Event probabilities sum into function

src/estimation/fdr/bh.rs, src/estimation/fdr/ev.rs, src/estimation/fdr/mod.rs
I found a little glitch from my downstream tests in prosolo: The new csv serializer automatically outputs the header automatically, based on field names. With the manual header output in our case, we got a double header and this patch restores previous behaviour. Should merge this before PR #22, which should be rebased after this is merged.
=> quick patch (omit double header for FDR thresholds)

src/model/evidence/fragments.rs, src/model/evidence/observation.rs, src/model/evidence/reads.rs, src/model/sample.rs
We unpack the cigar in the ReadBuffer. This way, it happens only once, instead of multiple times, e.g. for subsequent variants that share reads with the previous buffer window.
=> Unpack and reuse cigar

src/call/pairwise.rs, src/model/mod.rs, src/model/priors/flat.rs, src/model/priors/mod.rs, src/model/priors/single_cell_bulk.rs, src/model/priors/tumor_normal.rs
This introduces two likelihood caches into `PairPileup`, to avoid calculating the same likelihoods multiple times. So far this is only implemented for the `TumorNormalModel`, to first make it work before applying it to the other models, as well.
@johanneskoester: I hope this is a cleaner restart compared to before. I have tried around a lot of things and this is closest to working. The compiler now chokes on the two following spots (each with a line ahead shown for context, relevant is the bottom line):
https://github.com/PROSIC/libprosic/blob/6cb3d6d0d6be1d17476cad5e53dfef6d8726f81e/src/call/pairwise.rs#L203-L204
https://github.com/PROSIC/libprosic/blob/6cb3d6d0d6be1d17476cad5e53dfef6d8726f81e/src/call/pairwise.rs#L239-L240
In the current code state, it throws:
```
error[E0596]: cannot …
```
=> Likelihood caches via mutable pair pileup passing

src/model/mod.rs
Just as a quick explanation for the verbose new code: I first tried just substituting `or_insert()` with `or_insert_with()`, but the `Rust` ownership model doesn't allow that. `self` needs to be borrowed mutably in that context to allow the insertion to take place, and the call to `self.case_sample_model.likelihood_pileup()` is another (immutable) borrow while the other borrow is still active. Thus the funny scoping of `l` and all...
Also, this code leads to an ~80% runtime reduction in ProSolo:
https://github.com/ProSolo/prosolo/issues/2#issuecomment-407439622
=> Likelihood caches working

Cargo.toml, src/call/pairwise.rs, src/estimation/effective_mutation_rate.rs, src/lib.rs, src/model/evidence/mod.rs, src/model/priors/flat.rs, src/model/priors/single_cell_bulk.rs, src/model/priors/tumor_normal.rs, src/model/sample.rs, src/utils.rs, tests/lib.rs
This PR introduces the use of the [`cached` crate](https://docs.rs/cached) to cache the computations by the `single-cell-bulk` model function `prob_rho()`. This cache has to be defined outside of the model to allow for its mutability--but I could imagine a wrapper Trait and separate wrapper implementations of that that Trait for different whole genome amplification methods, should we include more at some point. For now, I would keep it as is.
=> prob_rho caching

src/model/mod.rs, tests/lib.rs
at both ends, one-sided exclusivity does not make sense.
=> ContinuousAlleleFreqs of points should be inclusive or exclusive

src/call/pairwise.rs, src/model/evidence/observation.rs, src/model/evidence/reads.rs, src/model/likelihood.rs, src/model/mod.rs, src/model/sample.rs
I implemented 4 optimisation ideas that @johanneskoester and I had, but only one of them gave any significant savings:
* creating the new field `prob_one_minus_mapping` in `Observation` that gets computed when a new observation is created -- thus, when a read is used multiple times (e.g. for multiple variants it spans or for the likelihood of different `Event`s) this is only calculated once and then just pulled up every time needed
This seems to shave another 15% off of the previous best prosolo runtime (on PR #46).
**Please double-check the changes, especially for `prob_one_minus_mapping` commit, as that changed different spots around the codebase, including some newer indel code!**
Here are the `time`s and flamegraphs, computed on a 1 Mb slice of `chr4` in an exome dataset, with timing …
=> Minimize ln operations

src/estimation/fdr/ev.rs, tests/lib.rs
This is a corner case I came across in prosolo, where I was controlling the probabilities for whole genome amplification errors that rarely are really high, meaning that using low alphas triggered this bug: If no entry has a probability high enough to pass above the respective threshold for that alpha, no filtering is applied at all, instead of filtering out all entries. This is what happens now.
=> fdr control: properly handle very low requested alphas and add test

Cargo.toml, src/estimation/alignment_properties.rs, src/estimation/effective_mutation_rate.rs, src/model/evidence/fragments.rs, src/model/evidence/reads.rs, src/model/likelihood.rs, src/model/mod.rs, src/model/priors/flat.rs, src/model/priors/mod.rs, src/model/priors/normal.rs, src/model/priors/single_cell_bulk.rs, src/model/priors/tumor_normal.rs, src/model/priors/tumor_normal_relapse.rs, src/model/sample.rs, src/utils.rs, tests/lib.rs
@dlaehnemann this is another round of optimizations in Rust-Bio. Again this PR includes the changes from #51 and #53. May I ask you for another flamegraph?
Thanks!
* Omit lower left and upper right triangle in pairHMM dynamic programming matrix if gap extension probability is zero. (#54)
* Try to skip as many LogProb operations as possible in pairHMM code. (#54)
* Use fast approximation of exp (#53).
* Use precomputed per-base match, mismatch and indel probabilities (#51).
* Calculate best edit distance with Myer's algorithm in linear time. Use that (times 2) as a bound for a banded pair-HMM. In particular for small indels (which usually cause performance bottlenecks because they are abundant), this should cause a huge speedup, because large parts of the matrix will be omitted (#54).
=> PairHMM optimizations

src/call/pairwise.rs, src/estimation/alignment_properties.rs, src/estimation/effective_mutation_rate.rs, src/model/evidence/fragments.rs, src/model/evidence/mod.rs, src/model/mod.rs, src/model/priors/flat.rs, src/model/priors/single_cell_bulk.rs, src/model/priors/tumor_normal.rs, src/model/sample.rs, src/utils.rs, tests/lib.rs
After a quick discussion, @johanneskoester and I decided that we feel comfortable with capping a numerical overshoot in log-space of up to 1e-04. So that's the new hard-coded value -- exposing this as a command-line parameter to the filtering functionality in prosic and prosolo would require significant extra work.
=> cap_numerical_overshoot: increase acceptable overshoot to 0.0001

src/call.rs, src/utils.rs
Tools like htsjdk fail in such cases. Although the standard allows it, it is uncommon enough to anticipate that htsjdk will not be the only one.
=> Avoid two <DEL> alleles in the same BCF record.

src/call.rs, src/conversion/decode_phred.rs, src/filtration/fdr.rs, src/filtration/posterior_odds.rs, src/utils.rs
- `decode-phred` converts from default PHRED scaled probabilities to non scaled unit probabilities but adds no information whether values are scaled or not, possibly leading to confusion
- the filtration tools, too, expect PHRED scaled quality values
- this PR appends either (PHRED) or (linear) to the description field of any event tag in the bcf header, e.g.:
-  `##INFO=<ID=PROB_GERMLINE_HET,Number=A,Type=Float,Description=Posterior probability for event germline_het>`
becomes
`##INFO=<ID=PROB_GERMLINE_HET,Number=A,Type=Float,Description=Posterior probability for event germline_het (PHRED)>` by default with this PR
-  running `decode-phred` leads to
`##INFO=<ID=PROB_GERMLINE_HET,Number=A,Type=Float,Description=Posterior probability for event germline_het (PHRED)>` (also without the …
=> State scale (PHRED / linear) on INFO fields in bcf header for event tags.

src/model/sample.rs
`an_array.into_iter()` currently just works because of the autoref
feature, which then calls `<[T] as IntoIterator>::into_iter`. But
in the future, arrays will implement `IntoIterator`, too. In order
to avoid problems in the future, the call is replaced by `iter()`
which is shorter and more explicit.
A crater run showed that your crate is affected by a potential future 
change. See https://github.com/rust-lang/rust/pull/65819 for more information.
=> Use `slice::iter` instead of `into_iter` to avoid future breakage

src/calling/variants/calling.rs, src/calling/variants/mod.rs, src/calling/variants/preprocessing/mod.rs, src/utils/mod.rs, src/variants/evidence/observation.rs, src/variants/model/bias/mod.rs, src/variants/model/bias/read_orientation_bias.rs, src/variants/model/bias/strand_bias.rs, src/variants/model/likelihood.rs, src/variants/model/mod.rs, src/variants/model/modes/generic.rs, src/variants/types/mod.rs
This enables us to detect Guanin oxidation errors.
=> Generalize bias handling. Add read orientation bias.

Cargo.toml, src/variants/evidence/bases.rs, src/variants/evidence/realignment/pairhmm.rs
This is slightly faster than calculating them on the fly.
=> Use precomputed base miscall and call likelihoods.

src/cli.rs, src/estimation/alignment_properties.rs, src/testcase.rs, src/variants/sample.rs, src/variants/sampling_bias/fragments.rs
When running varlociraptor on some single end read data, I got this panic!() that I had put there a while ago:
```
AlignmentProperties has insert_size set to `None`, but you are trying to use it without checking for None.This is a bug.
```
The backtrace indicates, that the problem is in `varlociraptor::variants::sample::SampleBuilder::alignments()`:
```
0: backtrace::backtrace::libunwind::trace
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
1: backtrace::backtrace::trace_unsynchronized
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
2: std::sys_common::backtrace::_print_fmt
at src/libstd/sys_common/backtrace.rs:78
3: <std::sys_common::backtrace::_print::DisplayBacktrace as …
```
=> remove possibility of using alignment_properties.insert_size when it is None

Cargo.lock, Cargo.toml, src/calling/variants/calling.rs, src/variants/model/prior.rs
Avoids an endless filling of the prior cache for complex scenarios.
=> Fix prior cache

src/cli.rs, src/estimation/tumor_mutational_burden.rs, templates/plots/vaf_curve_strat.json, templates/plots/vaf_hist.json, templates/plots/vaf_multi_bar.json
This PR seeks to enhance the TMB plotting functionality towards a multi-sample barplot. 
- Vartypes have been reduced to Signatures (T>C falls under the same category as A>G etc.), but the original code is still present - maybe it can be an optional choice which representation to use.
- For visibility, TMB in the multi-sample plot is shown for a minimal VAF value which can be chosen as a parameter.
This is just a first functional version to get a quick representation of multiple samples side by side.
=> TMB plots for multiple samples

.gitpod.yml, Dockerfile, README.md
[gitpod](https://gitpod.io/workspaces/) itself supplies a pretty good summary for this PR:
> This PR implements a fully-automated development setup using Gitpod.io, an
> online IDE for GitLab, GitHub, and Bitbucket that enables Dev-Environments-As-Code.
> This makes it easy for anyone to get a ready-to-code workspace for any branch,
> issue or pull request almost instantly with a single click.
The dependencies needed for tests (i.e. samtools) are contained in a pre-built environment with the name `varlociraptor` that is automatically activated in the first opened terminal. When opening a new terminal you can activate the environment manually with `micromamba activate varlociraptor`.
=> Add ready-to-code option with gitpod

src/conversion/decode_phred.rs
Otherwise, descriptions containing commas will lead to invalid header lines, as commas will be interpreted as field separators in the header line.
=> decode_phred: ensure quoting of description in changed header lines

src/variants/model/prior.rs
Analog to [this one at rust-bio](https://github.com/rust-bio/rust-bio/pull/430#event-4805686901), just with the `panic!` macro:
> Just a quick fix of for `#[warn(non_fmt_panic)]`. Looks like the `format!` macro should be avoided inside the `assert!` >as shown [here](https://doc.rust-lang.org/std/macro.assert.html#custom-messages) in the example for custom error >messages with `assert!`.
=> Fix compiler warning

src/grammar/formula.rs, src/grammar/mod.rs
testcase 71 sometimes fails because formula normalization via BDD is not deterministic.
=> fix: testcase 71 sometimes fails because formula normalization via BDD is not deterministic

src/calling/variants/calling.rs, src/calling/variants/mod.rs, src/calling/variants/preprocessing/mod.rs, src/cli.rs, src/conversion/decode_phred.rs, src/estimation/effective_mutation_rate.rs, src/estimation/mutational_burden.rs, src/grammar/formula.rs, src/grammar/mod.rs, src/grammar/vaftree.rs, src/testcase.rs, src/utils/anonymize.rs, src/utils/collect_variants.rs, src/utils/mod.rs, src/variants/evidence/insert_size.rs, src/variants/evidence/observation.rs, src/variants/evidence/realignment/mod.rs, src/variants/model/bias/read_position_bias.rs, src/variants/model/mod.rs, src/variants/model/modes/generic.rs, src/variants/model/modes/tumor.rs, src/variants/model/prior.rs, src/variants/sample.rs, src/variants/types/breakends.rs, src/variants/types/deletion.rs, src/variants/types/insertion.rs, src/variants/types/mnv.rs, src/variants/types/mod.rs, src/variants/types/replacement.rs, src/variants/types/snv.rs
This PR addresses some clippy lints, but notably does not fix the floating point comparison ones, since these are exact checks for 1.0 mostly. Perhaps one could check the floating point bits instead?
=> chore: Address some clippy lints

src/cli.rs, src/estimation/sample_variants.rs, templates/plots/vaf_scatter_contour.json
This PR removes the check for coding variants in the variant scatter plots. Now, all variants coding and non-coding should be considered.
=> fix: Removed check for coding variants

tests/common/mod.rs
This just fixes the testing which went missing when updating to `rust-htslib 0.38`.
=> chore: Fix CI test

tests/lib.rs
Previously, we did always allow a difference of 1 in the number of records. Now, this is only allowed if more than 50 records are expected.
=> test: fix fdr testcase logic

src/variants/evidence/observation.rs, src/variants/model/likelihood.rs, src/variants/model/modes/generic.rs, src/variants/model/prior.rs
use lru cache for likelihoods, skip formula tree branches if all observations indicate absence of a variant
=> perf: various speed improvements for scenario evaluations

src/variants/model/bias/mod.rs
This should speed up scenarios with missing samples by an order of magnitude.
=> perf: do not consider empty pileups for bias preprocessing

src/calling/variants/calling.rs, src/utils/mod.rs, src/variants/evidence/observation.rs, tests/resources/testcases/test05/testcase.yaml, tests/resources/testcases/test09/testcase.yaml, tests/resources/testcases/test10/testcase.yaml, tests/resources/testcases/test20/testcase.yaml, tests/resources/testcases/test22/testcase.yaml, tests/resources/testcases/test23/testcase.yaml, tests/resources/testcases/test30/testcase.yaml, tests/resources/testcases/test31/testcase.yaml, tests/resources/testcases/test_giab_20/testcase.yaml
This adds some additional uncertainty to low depth loci. This is important, because at low depth, we might accidentally miss low MAPQ reads and all observed reads could have an artificially inflated MAPQ by random sequencing errors. By adding a pseudo observation with reduced MAPQ, this missing uncertainty is efficiently introduced, while becoming more and more important the lower the depth is.
=> fix: use pseudo observation to adjust MAPQ for lower depths

src/errors.rs, src/variants/evidence/observation.rs
Currently varlociraptor fails when the strand information is absent in the strand-information-string.
Absent strand information is represented by `.`.
As the `Strand`-enum already contains `None` as possible object handling of the absent information only has the be added to the `from_aux_item`-function.
=> fix: handle absent strand information

src/calling/variants/calling.rs
This fixes a typo in the VCF header for FORMAT/AFD, where Number was given as `A` (i.e. one entry per allele); Number should be `.` instead, since there are a variable number of key=value pairs encoded in this tag and varlociraptor generates exactly one record per allele.
=> fix: Format field header for Allele Frequency Distribution should have `Number=.`, not `Number=A`

src/variants/evidence/observations/read_observation.rs, src/variants/model/bias/homopolymer_error.rs
We require all alt supporting samples to have at least one homopolymer indel relative to the alt allele.
=> fix: remove spurious homopolymer error calls

src/variants/evidence/realignment/edit_distance.rs
With rust-bio 0.39.2, the BitVec trait has `#[cfg(has_u128)]` checks, so we also do those checks.
=> fix: check if cfg has_u128 or not

src/calling/variants/calling.rs, src/utils/homopolymers.rs, tests/lib.rs
=> fix: only check for homopolymer errors if the indel operation is alone in the variant

src/grammar/formula.rs, src/variants/model/modes/generic.rs
=> fix: convert empty VAF spectrum to false and ensure that an empty spectrum evaluates as zero probability

src/cli.rs, src/estimation/alignment_properties.rs, src/variants/evidence/realignment/pairhmm.rs
This PR tackles two things:
1. If there are insufficient observations during parameter estimation for gaps and hops, use defaults instead
2. If there are probabilities of 0 in the gap/hop parameters, the log probabilities will be -inf, and -inf is serialized as null because json has no concept of +-inf and NaN. (We can either wrap these in some enum or perhaps switch to yaml)
=> fix: fix insufficient data leading to probabilities of 0 leading to nulls in alignment properties

src/errors.rs, src/utils/variant_buffer.rs
This PR includes the two loci which violate the `previous_locus <= current_locus` condition in the error.
=> chore: Make UnsortedVariantFile error more informative

src/calling/variants/preprocessing/mod.rs
This PR adjusts the `Number=X` information of the VCF header written in the preprocessing step such that it matches the VCF specification v4.3.
=> fix: Adhere to number specifications from VCF v4.3

src/calling/variants/preprocessing/haplotype_feature_index.rs, src/utils/mod.rs
=> fix: do not skip haplotype determination if SVTYPE tag is not present in VCF

src/errors.rs, src/variants/model/mod.rs
Before, only EVENT tags where supported. Now, also MATEID without an EVENT tag is enough to construct a pair of connected breakends.
=> feat: add MATEID based recognition of connected breakends

src/calling/variants/calling.rs, src/cli.rs, src/estimation/contamination.rs, src/testcase/runner/common/mod.rs, src/variants/model/likelihood.rs, src/variants/model/modes/generic.rs, src/variants/model/prior.rs
This results in more intuitive classifications, and also avoids pitfalls generated by very low mutation rates.
An example for such a pitfall is the case where the somatic mutation rate is set much lower in the normal sample than in a tumor sample. In such cases, it could have happened that Varlociraptor puts aside the evidence for the variant being somatic in the normal sample just because it is cheaper to consider it a tumor sample only variant. While this is statistically correct given the prior beliefs in that case, it makes the model very dependent on those priors being chosen correctly, which is in practice very difficult.
=> feat: by default, use prior to guard absence or presence of variant but weight all decisions about other events just by the observations

src/utils/homopolymers.rs
Homopolymer identification fails if an insertion shows up at the end of a reference due to misindexing.
This is fixed by checking the position first.
=> fix: fix homopolymer identification

src/utils/collect_variants.rs
This PR makes the `collect_variants` function public for reuse in another crate.
=> refactor: Make collect_variants public

src/calling/variants/preprocessing/mod.rs
=> fix: fix decompression of CRAM files that rely on an external reference FASTA. Varlociraptor now uses the given reference FASTA for this decompression

Cargo.lock, src/utils/homopolymers.rs, src/variants/evidence/observations/read_observation.rs, src/variants/model/bias/homopolymer_error.rs, src/variants/model/bias/strand_bias.rs, tests/resources/testcases/test19/testcase.yaml, tests/resources/testcases/test_giab_19/testcase.yaml, tests/resources/testcases/test_giab_35/testcase.yaml, tests/resources/testcases/test_pcr_homopolymer_error2/testcase.yaml, tests/resources/testcases/test_pcr_homopolymer_error3/testcase.yaml
fix: overhaul of homopolymer error model. Main idea: ignore fragments that either support ref or alt without homopolymer error. For the rest, rely on observed errors overall and compare which center of the error distribution better fits the observed homopolymer errors, the variant or the reference allele.
fix: calculate strand bias for cases where there is already a strong bias in the ref fragments, if that bias can be reliably estimated because there are enough supporting fragments.
=> fix: complete overhaul of homopolymer error model (to be more specific) and fix for strand bias model (to be more sensitive)

Cargo.lock, src/variants/evidence/observations/read_observation.rs, src/variants/sample.rs, src/variants/types/breakends.rs, src/variants/types/deletion.rs, src/variants/types/insertion.rs, src/variants/types/mnv.rs, src/variants/types/mod.rs, src/variants/types/none.rs, src/variants/types/replacement.rs, src/variants/types/snv.rs
Added support for optical mapping data.
=> feat: optical mapping support
